[package]
name = "test-no-std"
version = "0.6.0"
authors = ["Alain Brenzikofer <alain.brenzikofer@scs.ch>"]
edition = "2021"

[dependencies]
libc = { version = "0.2.119", default-features = false }

# local dependencies
ac-node-api = { path = "../node-api", default-features = false, optional = true }
substrate-api-client = { path = "..", default-features = false, optional = true }

# substrate dependencies
sp-io = { version = "6.0.0", default-features = false, features = ["disable_oom", "disable_panic_handler"], git = "https://github.com/paritytech/substrate.git", branch = "master" }

[features]
# it is better to test the no-std crates standalone because dependency leaks might cause
# successful `no-std` builds, which would fail in standalone build.
api-client = ["substrate-api-client"]
node-api = ["ac-node-api"]